name: Update Threat Feeds

on:
  schedule:
    - cron: '0 3 * * *'   # ежедневно в 03:00 UTC
  workflow_dispatch:       # ручной запуск с кнопки

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt || true

      - name: Run aggregator
        run: python scripts/aggregator.py

      - name: Generate metadata
        run: python scripts/generate_metadata.py

      - name: Commit and push
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "GitHub Action"
          git add feeds/*.txt feeds/metadata.json
          git commit -m "chore: update feeds and metadata [bot]" || echo "No changes to commit"
          git push