name: Update Threat Feeds

on:
  schedule:
    - cron: '0 3 * * *'   # ежедневно в 03:00 UTC
  workflow_dispatch:       # ручной запуск с кнопки

jobs:
  update-feeds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run aggregator
        run: python scripts/aggregator.py

      - name: Commit and push updates
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add feeds/*.txt
          git commit -m "chore: auto-update feeds" || echo "No changes to commit"
          git push